# Generated by Django 5.0.2 on 2024-02-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('book_no', models.IntegerField(primary_key=True, serialize=False)),
                ('book_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
